#! /usr/bin/env python
#
"""
USAGE: focas_ifu_biassub -t bias_template -o output.fits right.fits left.fits

  right.fits: right image file name (smaller file number)
  left.fits: left image file name (larger file number)
  output.fits: output file name
  -t arg: prefix of the bias template files
"""
import sys
from optparse import OptionParser

from naoj.focas.biassub import biassub
from naoj.focas.focasifu import version


def main(options, args):

    hdulst = biassub(args[0], args[1],
                     template_pfx=options.template_pfx)

    # Writing the output fits file
    if hdulst:
        hdulst.writeto(options.outputfile, overwrite=True)

if __name__ == '__main__':
    # Parse command line options with optparse module

    usage = "usage: %prog [options] ch1.fits ch2.fits"
    optprs = OptionParser(usage=usage,
                          version=('%%prog %s' % version))

    optprs.add_option("-o", "--outputfile", dest="outputfile", metavar="NAME",
                      default='output.fits',
                      help="Specify output file name")
    optprs.add_option("-t", "--template_pfx", dest="template_pfx", metavar="NAME",
                      default='bias_template',
                      help="Specify bias template prefix")
    (options, args) = optprs.parse_args(sys.argv[1:])

    main(options, args)
