#! /usr/bin/env python
#
import sys
import argparse

from naoj.focas.mkbiastemplate import MkTwoBiasTemplate

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='This is the script for making bias template files..')
    parser.add_argument('filename',help='Bias FITS file')
    parser.add_argument('-o', help='Overwrite flag', dest='overwrite',
                    action='store_true', default=False)
    parser.add_argument('-d', help='Raw data directory',
                        dest='rawdatadir', action='store', default='')
    args = parser.parse_args()

    MkTwoBiasTemplate(args.filename, rawdatadir=args.rawdatadir,
                      overwrite=args.overwrite)
